"""v2 weekly_reports comparisons personality

Revision ID: 4385841853d3
Revises: 6a070329b414
Create Date: 2026-06-06 18:18:58.899768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4385841853d3'
down_revision: Union[str, Sequence[str], None] = '6a070329b414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_comparisons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('prompt_a', sa.Text(), nullable=False),
    sa.Column('prompt_b', sa.Text(), nullable=False),
    sa.Column('score_a', sa.Float(), nullable=True),
    sa.Column('score_b', sa.Float(), nullable=True),
    sa.Column('scores_a', sa.JSON(), nullable=True),
    sa.Column('scores_b', sa.JSON(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_comparisons_user_id'), 'prompt_comparisons', ['user_id'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_prompts', sa.Integer(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('best_category', sa.String(), nullable=True),
    sa.Column('worst_category', sa.String(), nullable=True),
    sa.Column('improvement_pct', sa.Float(), nullable=True),
    sa.Column('top_mistakes', sa.JSON(), nullable=True),
    sa.Column('coaching_suggestions', sa.JSON(), nullable=True),
    sa.Column('dimension_avgs', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reports_user_id'), 'weekly_reports', ['user_id'], unique=False)
    op.add_column('users', sa.Column('personality_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('personality_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'personality_updated_at')
    op.drop_column('users', 'personality_type')
    op.drop_index(op.f('ix_weekly_reports_user_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_prompt_comparisons_user_id'), table_name='prompt_comparisons')
    op.drop_table('prompt_comparisons')
    # ### end Alembic commands ###
