"""v2 features: weekly_reports, comparisons, personality

Revision ID: 4c5c14ee7edb
Revises: 4385841853d3
Create Date: 2026-06-06 18:19:47.329616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5c14ee7edb'
down_revision: Union[str, Sequence[str], None] = '4385841853d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
