"""initial schema — users, prompts, scores, coaching, feedback

Revision ID: 6a070329b414
Revises: c5901e681a55
Create Date: 2026-06-06 10:27:03.812501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a070329b414'
down_revision: Union[str, Sequence[str], None] = 'c5901e681a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_dimension', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_insights_user_id'), 'coaching_insights', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('was_helpful', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_prompt_id'), 'feedback', ['prompt_id'], unique=False)
    op.add_column('prompt_logs', sa.Column('coaching_tip', sa.Text(), nullable=True))
    op.add_column('prompt_logs', sa.Column('success_probability', sa.Integer(), nullable=True))
    op.add_column('prompt_logs', sa.Column('success_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_logs', 'success_reason')
    op.drop_column('prompt_logs', 'success_probability')
    op.drop_column('prompt_logs', 'coaching_tip')
    op.drop_index(op.f('ix_feedback_prompt_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_coaching_insights_user_id'), table_name='coaching_insights')
    op.drop_table('coaching_insights')
    # ### end Alembic commands ###
