"""v2 features: weekly_reports, comparisons, personality

Revision ID: f96e55fd133e
Revises: 4c5c14ee7edb
Create Date: 2026-06-06 18:23:02.198927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96e55fd133e'
down_revision: Union[str, Sequence[str], None] = '4c5c14ee7edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
